settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统正常运行'
  notAllmonitorsOperational: '部分系统离线'
  monitorLabelOperational: '正常运行'
  monitorLabelNotOperational: '离线'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' 部分检查失败' # xx incident(s) recorded

monitors:
  - id: alist-cwlindean-top
    name: cdn.hoshino123.eu.org
    url: 'https://alist.hoshino123.eu.org:52199'
    method: GET
    expectStatus: 200
    linkable: true

  - id: page-cwlindean-top
    name: page.cwlindean.top
    url: 'https://page.cwlindean.top/'
    method: GET
    expectStatus: 200
    linkable: false
    
